version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: social_media
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: nestjs-api
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/social_media?authSource=admin
      PORT: 5002

volumes:
  mongo-data:
